### ISSUE TITLE
Automation to turn off appliances is unreliable

### ISSUE THREAD

**Issue by shortbloke** [shortbloke/home_assistant_config#18]
The current automation scripts to turn of sockets if no moment detected for > 30mins AND the socket is drawing current (i.e. so we know the  appliance is on, and don't turn off at the wall). 

However this is open failure as if the appliance, in my case an Iron, which has a thermostat which turns on and off. So at the 30min point it's possible the current draw is low enough not to trigger.

Need to review at reversing the check as whilst power state may fluctuate a timer for how long the room has been empty would continue to grow. Needs some research into what the existing automation structure can provide, or if a new template sensor needs to be defined to capture the idle state/time.

Example automation script:
```
- id: a_IronOn_2
  alias: Ironing Room No Motion Turn off Irons Left
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_2_power.state | int > 10 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_2
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected Turning off Ironing room Irons (Left)"
```
