### ISSUE TITLE
Add Dyson Fan and associated sensors as package

### ISSUE THREAD

**Issue by shortbloke** [shortbloke/home_assistant_config#35]
Move configuration from config dir to packages dir and sensors. Derive sensors from:
Air Quality
```
air_quality.bedroom:
 - air_quality_index: 12 
 - attribution: Dyson purifier air quality sensor
 - nitrogen_dioxide: 0 
 - particulate_matter_10: 8 
 - particulate_matter_2_5: 12 
 - volatile_organic_compounds: 4 
 - friendly_name: Bedroom
```
Fan
```

fan.bedroom: 
- speed: medium 
 - speed_list: low,medium,high 
 - oscillating: false 
 - night_mode: false 
 - auto_mode: false 
 - angle_low: 157 
 - angle_high: 202 
 - flow_direction_front: true 
 - timer: OFF 
 - hepa_filter: 88 
 - carbon_filter: 88 
 - dyson_speed: 6 
 - dyson_speed_list: 1,2,3,4,5,6,7,8,9,10 
 - friendly_name: Bedroom
 - supported_features: 3
```
Customise names and icons
